style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/terraform-module/terraform-aws-enforce-mfa
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
