name: commit-check
# This workflow is triggered on pushes to the repository.
on: [push, pull_request, issues]

jobs:
  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '1'
      - run: |
          terraform fmt --recursive -check=true

  docs:
    name: pre-commit-hook
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '1'
      - name: Install Deps
        run: |
          brew install pre-commit terraform-docs terraform tflint
      - name: Check All Files
        run: |
          pre-commit run --all-files
